### ISSUE TITLE
In reanalyze_worker GPU worker, why prepare policy targets and value targets separately?

### ISSUE THREAD

**Issue by desaixie** [YeWR/EfficientZero#38]
Why prepare policy targets and value targets separately? The two functions both run initial inference and a MCTS search to get either the root distributions or the root values. Why not get them using a single initial inference and MCTS search to save computation?

**Comment by YeWR** [comment]
The policy target requires the policy distribution of $s_t$ while the value target requires the value of $s_{t+k}$. That's because the value target is obtained through bootstrapping: $v_t = r_t + \gamma r_{t+1} + ... + \gamma^{k-1} r_{t+k-1} + \gamma^k v_{t+k}$, where $v_{t+k}$ is obtained by MCTS or the value network. Therefore, the policy target and the value target cannot be calculated from the same search Tree simultaneously.

**Comment by desaixie** [comment]
Thanks for the reply. I actually realized this myself while I read more into the code, but your reply definitely helps to confirm my understanding.
